package main

func main() {
	err := recover()
	println(err)
}

